import { Heading, Text, Button, MenuItem, FormControl, Select, Image, Container, Spacer } from '@chakra-ui/react'
import { Head } from 'components/layout/Head'
import React, { useEffect, useRef, useState } from 'react'
import { Configuration, ImagesResponseDataInner, OpenAIApi } from 'openai'
import { useContractWrite, usePrepareContractWrite, useWaitForTransaction } from 'wagmi'
import { ethers } from 'ethers'
import abi from '../../../constants/abi.json'
import css from '../../styles/mint.module.css'
import { Address, readContract } from '@wagmi/core'
import { useDebounce } from 'usehooks-ts'
import CreateFighter from 'components/mint/CreateFighter'
import MintFighter from 'components/mint/MintFighter'

export default function Mint() {
  // const [images, setImages] = useState<ImagesResponseDataInner[]>([])
  // const debouncedTokenId = useDebounce(tokenUrl, 500)

  const [base64String, setBase64String] = useState('')
  const [imagesBinaryData, setImagesBinaryData] = useState<ImagesResponseDataInner[]>([])

  const ipfsGatewayReplace = (url: string) => {
    return url.replace(/^ipfs:\/\//, 'https://ipfs.io/ipfs/')
  }

  return (
    <>
      <Head />
      <main>
        <Heading as="h2">Mint Page</Heading>
        <Text>
          Welcome to the Ultimate Fighting Metaverse NFT mint page! It&apos;s time to create your very own digital asset representing your ultimate
          fighter. Plus, each NFT is one-of-a-kind, generated by the amazing DALL-E. Are you ready to prove your worth in the ring? Let&apos;s do
          this!
        </Text>
        <Container className={css.root}>
          <Container className={css.container}>
            <CreateFighter setImagesBinaryData={setImagesBinaryData} />
            <Spacer m="16px" />
            <MintFighter imagesBinaryData={imagesBinaryData} />
            <br />
          </Container>
        </Container>
      </main>
    </>
  )
}
